apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana
  labels:
    app.kubernetes.io/name: grafana
spec:
  resources:
    requests:
      storage: 2Gi
  accessModes:
    - ReadWriteOnce